import Foundation
import AppBundle

public enum GRVMgramStringKey: String, CaseIterable {
    case brandName = "GRVMgram.Brand.Name"
    case settingsTitle = "GRVMgram.Settings.Title"
    case mainCore = "GRVMgram.Main.Core"
    case mainFilters = "GRVMgram.Main.Filters"
    case mainGeneral = "GRVMgram.Main.General"
    case mainAppearance = "GRVMgram.Main.Appearance"
    case mainChats = "GRVMgram.Main.Chats"
    case mainOther = "GRVMgram.Main.Other"
    case mainDeleted = "GRVMgram.Main.Deleted"
    case mainHistory = "GRVMgram.Main.History"

    case commonDefault = "GRVMgram.Common.Default"
    case commonOff = "GRVMgram.Common.Off"
    case commonHidden = "GRVMgram.Common.Hidden"
    case commonShown = "GRVMgram.Common.Shown"
    case commonWithModifier = "GRVMgram.Common.WithModifier"
    case commonNever = "GRVMgram.Common.Never"
    case commonInGhost = "GRVMgram.Common.InGhost"
    case commonAlways = "GRVMgram.Common.Always"
    case commonSearch = "GRVMgram.Common.Search"
    case commonClear = "GRVMgram.Common.Clear"
    case commonExport = "GRVMgram.Common.Export"
    case commonImport = "GRVMgram.Common.Import"

    case coreTitle = "GRVMgram.Core.Title"
    case ghostHeader = "GRVMgram.Ghost.Header"
    case ghostMaster = "GRVMgram.Ghost.Master"
    case ghostReadReceipts = "GRVMgram.Ghost.ReadReceipts"
    case ghostStoryViews = "GRVMgram.Ghost.StoryViews"
    case ghostOnline = "GRVMgram.Ghost.Online"
    case ghostTyping = "GRVMgram.Ghost.Typing"
    case ghostUpload = "GRVMgram.Ghost.Upload"
    case ghostAutoOffline = "GRVMgram.Ghost.AutoOffline"
    case ghostLockedComponents = "GRVMgram.Ghost.LockedComponents"
    case ghostLockedCount = "GRVMgram.Ghost.LockedCount"
    case ghostComponentReadReceipts = "GRVMgram.Ghost.Component.ReadReceipts"
    case ghostComponentStoryViews = "GRVMgram.Ghost.Component.StoryViews"
    case ghostComponentOnlineStatus = "GRVMgram.Ghost.Component.OnlineStatus"
    case ghostComponentTypingUploads = "GRVMgram.Ghost.Component.TypingUploads"
    case ghostComponentAutoOffline = "GRVMgram.Ghost.Component.AutoOffline"
    case ghostReadOnAction = "GRVMgram.Ghost.ReadOnAction"
    case ghostReadOnActionInfo = "GRVMgram.Ghost.ReadOnAction.Info"
    case ghostStoryPrompt = "GRVMgram.Ghost.StoryPrompt"
    case ghostStoryPromptInfo = "GRVMgram.Ghost.StoryPrompt.Info"
    case ghostSchedule = "GRVMgram.Ghost.Schedule"
    case ghostScheduleInfo = "GRVMgram.Ghost.Schedule.Info"
    case ghostSilent = "GRVMgram.Ghost.Silent"
    case ghostSilentInfo = "GRVMgram.Ghost.Silent.Info"
    case ghostActiveCount = "GRVMgram.Ghost.ActiveCount"
    case spyHeader = "GRVMgram.Spy.Header"
    case spySaveDeleted = "GRVMgram.Spy.SaveDeleted"
    case spySaveEdits = "GRVMgram.Spy.SaveEdits"
    case spySaveBots = "GRVMgram.Spy.SaveBots"
    case coreOtherHeader = "GRVMgram.Core.Other.Header"
    case coreLocalPremium = "GRVMgram.Core.LocalPremium"
    case coreDisableAds = "GRVMgram.Core.DisableAds"

    case filtersTitle = "GRVMgram.Filters.Title"
    case filtersHeader = "GRVMgram.Filters.Header"
    case filtersEnable = "GRVMgram.Filters.Enable"
    case filtersInChats = "GRVMgram.Filters.InChats"
    case filtersBlocked = "GRVMgram.Filters.Blocked"
    case filtersPatterns = "GRVMgram.Filters.Patterns"
    case filtersAdd = "GRVMgram.Filters.Add"
    case filtersAddPrompt = "GRVMgram.Filters.AddPrompt"
    case filtersEditPrompt = "GRVMgram.Filters.EditPrompt"
    case filtersReversed = "GRVMgram.Filters.Reversed"
    case filtersAddReversed = "GRVMgram.Filters.AddReversed"
    case filtersAddReversedPrompt = "GRVMgram.Filters.AddReversedPrompt"
    case filtersEditReversedPrompt = "GRVMgram.Filters.EditReversedPrompt"
    case filtersGlobal = "GRVMgram.Filters.Global"
    case filtersCaseSensitive = "GRVMgram.Filters.CaseSensitive"
    case filtersType = "GRVMgram.Filters.Type"
    case filtersButton = "GRVMgram.Filters.Button"
    case filtersSelectChat = "GRVMgram.Filters.SelectChat"
    case filtersShowFiltered = "GRVMgram.Filters.ShowFiltered"
    case filtersHideFiltered = "GRVMgram.Filters.HideFiltered"
    case filtersClear = "GRVMgram.Filters.Clear"
    case filtersStateNormal = "GRVMgram.Filters.State.Normal"
    case filtersStateReversed = "GRVMgram.Filters.State.Reversed"
    case filtersCaseInsensitive = "GRVMgram.Filters.CaseInsensitive"
    case filtersScopeAllChats = "GRVMgram.Filters.Scope.AllChats"
    case filtersScopeChat = "GRVMgram.Filters.Scope.Chat"
    case filtersExcludedCount = "GRVMgram.Filters.ExcludedCount"
    case filtersEmpty = "GRVMgram.Filters.Empty"
    case filtersBackupHeader = "GRVMgram.Filters.Backup.Header"
    case filtersImportTitle = "GRVMgram.Filters.Import.Title"
    case filtersImportSummary = "GRVMgram.Filters.Import.Summary"
    case filtersImportReplace = "GRVMgram.Filters.Import.Replace"
    case filtersInvalidFileTitle = "GRVMgram.Filters.InvalidFile.Title"
    case filtersInvalidFileText = "GRVMgram.Filters.InvalidFile.Text"
    case filtersClearTitle = "GRVMgram.Filters.Clear.Title"
    case filtersClearText = "GRVMgram.Filters.Clear.Text"
    case filtersMatchingTitle = "GRVMgram.Filters.Matching.Title"
    case filtersPeople = "GRVMgram.Filters.People"

    case filterEditorAddTitle = "GRVMgram.FilterEditor.AddTitle"
    case filterEditorEditTitle = "GRVMgram.FilterEditor.EditTitle"
    case filterEditorExpressionHeader = "GRVMgram.FilterEditor.Expression.Header"
    case filterEditorExpressionPlaceholder = "GRVMgram.FilterEditor.Expression.Placeholder"
    case filterEditorOptionsHeader = "GRVMgram.FilterEditor.Options.Header"
    case filterEditorEnabled = "GRVMgram.FilterEditor.Enabled"
    case filterEditorReversed = "GRVMgram.FilterEditor.Reversed"
    case filterEditorCaseInsensitive = "GRVMgram.FilterEditor.CaseInsensitive"
    case filterEditorScopeHeader = "GRVMgram.FilterEditor.Scope.Header"
    case filterEditorScopeChat = "GRVMgram.FilterEditor.Scope.Chat"
    case filterEditorScopeAllChats = "GRVMgram.FilterEditor.Scope.AllChats"
    case filterEditorScopeUseAllChats = "GRVMgram.FilterEditor.Scope.UseAllChats"
    case filterEditorExcludedChats = "GRVMgram.FilterEditor.ExcludedChats"
    case filterEditorNone = "GRVMgram.FilterEditor.None"
    case filterEditorClearExcluded = "GRVMgram.FilterEditor.ClearExcluded"
    case filterEditorSelectChat = "GRVMgram.FilterEditor.SelectChat"
    case filterEditorExcludeChats = "GRVMgram.FilterEditor.ExcludeChats"
    case filterEditorInvalidTitle = "GRVMgram.FilterEditor.Invalid.Title"
    case filterEditorInvalidText = "GRVMgram.FilterEditor.Invalid.Text"

    case shadowTitle = "GRVMgram.Shadow.Title"
    case shadowIds = "GRVMgram.Shadow.IDs"
    case shadowAdd = "GRVMgram.Shadow.Add"
    case shadowAddPrompt = "GRVMgram.Shadow.AddPrompt"
    case shadowEditPrompt = "GRVMgram.Shadow.EditPrompt"
    case shadowEmpty = "GRVMgram.Shadow.Empty"
    case shadowUnban = "GRVMgram.Shadow.Unban"
    case shadowAuthor = "GRVMgram.Shadow.Author"
    case shadowForwardedAuthor = "GRVMgram.Shadow.ForwardedAuthor"
    case shadowActionWithRole = "GRVMgram.Shadow.ActionWithRole"

    case generalTitle = "GRVMgram.General.Title"
    case translationHeader = "GRVMgram.Translation.Header"
    case translationProvider = "GRVMgram.Translation.Provider"
    case translationTelegram = "GRVMgram.Translation.Telegram"
    case translationGoogle = "GRVMgram.Translation.Google"
    case translationYandex = "GRVMgram.Translation.Yandex"
    case translationPrivacy = "GRVMgram.Translation.Privacy"
    case generalHeader = "GRVMgram.General.Header"
    case generalHideStories = "GRVMgram.General.HideStories"
    case generalSimilarChannels = "GRVMgram.General.SimilarChannels"
    case generalNotificationDelay = "GRVMgram.General.NotificationDelay"
    case generalSeconds = "GRVMgram.General.Seconds"
    case generalPeerId = "GRVMgram.General.PeerID"
    case generalZalgo = "GRVMgram.General.Zalgo"
    case generalLinkPreviews = "GRVMgram.General.LinkPreviews"
    case generalLinkWarning = "GRVMgram.General.LinkWarning"
    case peerIdApi = "GRVMgram.General.PeerID.API"
    case peerIdBotApi = "GRVMgram.General.PeerID.BotAPI"
    case webviewHeader = "GRVMgram.Webview.Header"
    case webviewAndroid = "GRVMgram.Webview.Android"
    case webviewHeight = "GRVMgram.Webview.Height"
    case webviewWidth = "GRVMgram.Webview.Width"
    case confirmationsHeader = "GRVMgram.Confirmations.Header"
    case confirmationsSticker = "GRVMgram.Confirmations.Sticker"
    case confirmationsGif = "GRVMgram.Confirmations.GIF"
    case confirmationsVoice = "GRVMgram.Confirmations.Voice"

    case appearanceTitle = "GRVMgram.Appearance.Title"
    case appIconHeader = "GRVMgram.AppIcon.Header"
    case appIconTitle = "GRVMgram.AppIcon.Title"
    case appIconDefault = "GRVMgram.AppIcon.Default"
    case appIconBlack = "GRVMgram.AppIcon.Black"
    case appIconBlackClassic = "GRVMgram.AppIcon.BlackClassic"
    case appIconBlackFilled = "GRVMgram.AppIcon.BlackFilled"
    case appIconBlue = "GRVMgram.AppIcon.Blue"
    case appIconBlueClassic = "GRVMgram.AppIcon.BlueClassic"
    case appIconBlueFilled = "GRVMgram.AppIcon.BlueFilled"
    case appIconWhiteFilled = "GRVMgram.AppIcon.WhiteFilled"
    case appIconNew1 = "GRVMgram.AppIcon.New1"
    case appIconNew2 = "GRVMgram.AppIcon.New2"
    case appIconPremium = "GRVMgram.AppIcon.Premium"
    case appIconPremiumBlack = "GRVMgram.AppIcon.PremiumBlack"
    case appIconPremiumTurbo = "GRVMgram.AppIcon.PremiumTurbo"
    case appearanceHideBadge = "GRVMgram.Appearance.HideBadge"
    case appearanceHideCounters = "GRVMgram.Appearance.HideCounters"
    case appearanceHeader = "GRVMgram.Appearance.Header"
    case appearanceMd3 = "GRVMgram.Appearance.MD3"
    case appearanceTail = "GRVMgram.Appearance.Tail"
    case appearanceBackgrounds = "GRVMgram.Appearance.Backgrounds"
    case appearanceCodeFont = "GRVMgram.Appearance.CodeFont"
    case appearanceAvatarCorners = "GRVMgram.Appearance.AvatarCorners"
    case appearanceBubbleRadius = "GRVMgram.Appearance.BubbleRadius"
    case appearanceSingleCorner = "GRVMgram.Appearance.SingleCorner"
    case appearancePremiumStatuses = "GRVMgram.Appearance.PremiumStatuses"
    case appearanceAdaptiveSavedMusicColor = "GRVMgram.Appearance.AdaptiveSavedMusicColor"
    case appearanceFolders = "GRVMgram.Appearance.Folders"
    case appearanceFolderCounters = "GRVMgram.Appearance.FolderCounters"
    case appearanceAllChats = "GRVMgram.Appearance.AllChats"

    case chatsTitle = "GRVMgram.Chats.Title"
    case stickersHeader = "GRVMgram.Chats.Stickers.Header"
    case stickersOnlyAdded = "GRVMgram.Chats.Stickers.OnlyAdded"
    case stickersChannelReactions = "GRVMgram.Chats.Stickers.ChannelReactions"
    case stickersGroupReactions = "GRVMgram.Chats.Stickers.GroupReactions"
    case stickersPrivateReactions = "GRVMgram.Chats.Stickers.PrivateReactions"
    case stickersRecent = "GRVMgram.Chats.Stickers.Recent"
    case channelsHeader = "GRVMgram.Chats.Channels.Header"
    case channelsQuickAdmin = "GRVMgram.Chats.Channels.QuickAdmin"
    case channelsMessageShot = "GRVMgram.Chats.Channels.MessageShot"
    case channelsBottomButton = "GRVMgram.Chats.Channels.BottomButton"
    case channelsBottomHide = "GRVMgram.Chats.Channels.BottomButton.Hide"
    case channelsBottomMute = "GRVMgram.Chats.Channels.BottomButton.Mute"
    case channelsBottomDiscuss = "GRVMgram.Chats.Channels.BottomButton.Discuss"
    case messagesHeader = "GRVMgram.Chats.Messages.Header"
    case deletedMark = "GRVMgram.Chat.DeletedMark"
    case deletedMarkVisible = "GRVMgram.Chat.DeletedMark.Visible"
    case deletedMarkPrompt = "GRVMgram.Chat.DeletedMark.Prompt"
    case deletedMarkDefault = "GRVMgram.Chat.DeletedMark.Default"
    case editedMark = "GRVMgram.Chat.EditedMark"
    case editedMarkVisible = "GRVMgram.Chat.EditedMark.Visible"
    case editedMarkPrompt = "GRVMgram.Chat.EditedMark.Prompt"
    case editedMarkDefault = "GRVMgram.Chat.EditedMark.Default"
    case messagesIcons = "GRVMgram.Chats.Messages.Icons"
    case messagesFastShare = "GRVMgram.Chats.Messages.FastShare"
    case messagesColoredReplies = "GRVMgram.Chats.Messages.ColoredReplies"
    case messagesWidth = "GRVMgram.Chats.Messages.Width"
    case messagesTranslucent = "GRVMgram.Chats.Messages.Translucent"
    case contextHeader = "GRVMgram.Chats.Context.Header"
    case contextReactions = "GRVMgram.Chats.Context.Reactions"
    case contextViews = "GRVMgram.Chats.Context.Views"
    case contextHide = "GRVMgram.Chats.Context.Hide"
    case contextUserMessages = "GRVMgram.Chats.Context.UserMessages"
    case contextDetails = "GRVMgram.Chats.Context.Details"
    case contextRepeat = "GRVMgram.Chats.Context.Repeat"
    case contextAddFilter = "GRVMgram.Chats.Context.AddFilter"
    case contextMoreActions = "GRVMgram.Chats.Context.MoreActions"
    case fieldHeader = "GRVMgram.Chats.Field.Header"
    case fieldAttach = "GRVMgram.Chats.Field.Attach"
    case fieldAttachPopup = "GRVMgram.Chats.Field.AttachPopup"
    case fieldCommands = "GRVMgram.Chats.Field.Commands"
    case fieldTtl = "GRVMgram.Chats.Field.TTL"
    case fieldEmoji = "GRVMgram.Chats.Field.Emoji"
    case fieldEmojiPopup = "GRVMgram.Chats.Field.EmojiPopup"
    case fieldVoice = "GRVMgram.Chats.Field.Voice"
    case fieldGift = "GRVMgram.Chats.Field.Gift"
    case fieldAi = "GRVMgram.Chats.Field.AI"

    case deletedTitle = "GRVMgram.Deleted.Title"
    case deletedEmpty = "GRVMgram.Deleted.Empty"
    case deletedRecent = "GRVMgram.Deleted.Recent"
    case deletedMessageEmpty = "GRVMgram.Deleted.MessageEmpty"
    case deletedMedia = "GRVMgram.Deleted.Media"
    case deletedMediaWithText = "GRVMgram.Deleted.MediaWithText"
    case deletedAuthor = "GRVMgram.Deleted.Author"
    case deletedAttachment = "GRVMgram.Deleted.Attachment"
    case deletedMediaUnavailable = "GRVMgram.Deleted.MediaUnavailable"
    case deletedArchivedResources = "GRVMgram.Deleted.ArchivedResources"
    case deletedClearTitle = "GRVMgram.Deleted.Clear.Title"
    case deletedClearText = "GRVMgram.Deleted.Clear.Text"
    case deletedClearAction = "GRVMgram.Deleted.Clear.Action"
    case deletedClearErrorTitle = "GRVMgram.Deleted.Clear.ErrorTitle"
    case deletedClearArchiveUnavailable = "GRVMgram.Deleted.Clear.ArchiveUnavailable"
    case deletedClearMediaRemovalFailed = "GRVMgram.Deleted.Clear.MediaRemovalFailed"
    case deletedClearDatabaseFinalizationFailed = "GRVMgram.Deleted.Clear.DatabaseFinalizationFailed"

    case historyTitle = "GRVMgram.History.Title"
    case historyInfo = "GRVMgram.History.Info"
    case historyEmpty = "GRVMgram.History.Empty"
    case historyMessageEmpty = "GRVMgram.History.MessageEmpty"
    case historyRecent = "GRVMgram.History.Recent"
    case historyCurrent = "GRVMgram.History.Current"
    case historyRevision = "GRVMgram.History.Revision"
    case historyAction = "GRVMgram.History.Action"
    case historyEntryHeader = "GRVMgram.History.EntryHeader"
    case historyArchivedResources = "GRVMgram.History.ArchivedResources"
    case historyMediaTodo = "GRVMgram.History.Media.Todo"
    case historyMediaPoll = "GRVMgram.History.Media.Poll"
    case historyMediaLinkPreview = "GRVMgram.History.Media.LinkPreview"
    case historyMediaFile = "GRVMgram.History.Media.File"
    case historyMediaPhoto = "GRVMgram.History.Media.Photo"
    case historyMediaGame = "GRVMgram.History.Media.Game"
    case historyMediaPaid = "GRVMgram.History.Media.Paid"
    case historyMediaContact = "GRVMgram.History.Media.Contact"
    case historyMediaLocation = "GRVMgram.History.Media.Location"
    case historyMediaInvoice = "GRVMgram.History.Media.Invoice"

    case chatMenuTitle = "GRVMgram.ChatMenu.Title"
    case chatMenuViewDeleted = "GRVMgram.ChatMenu.ViewDeleted"
    case chatMenuClearDeleted = "GRVMgram.ChatMenu.ClearDeleted"
    case menuLocalHide = "GRVMgram.Menu.LocalHide"
    case menuUserMessages = "GRVMgram.Menu.UserMessages"
    case menuDetails = "GRVMgram.Menu.Details"
    case menuRepeat = "GRVMgram.Menu.Repeat"
    case menuAddFilter = "GRVMgram.Menu.AddFilter"
    case menuViewFilters = "GRVMgram.Menu.ViewFilters"
    case menuHistory = "GRVMgram.Menu.History"
    case menuDeleteOwn = "GRVMgram.Menu.DeleteOwn"
    case menuReadMessage = "GRVMgram.Menu.ReadMessage"
    case menuReadAllLocal = "GRVMgram.Menu.ReadAllLocal"
    case menuReadAllServer = "GRVMgram.Menu.ReadAllServer"
    case menuBurn = "GRVMgram.Menu.Burn"
    case menuReplay = "GRVMgram.Menu.Replay"
    case menuForwardLocalCopy = "GRVMgram.Menu.ForwardLocalCopy"
    case menuSendAsSticker = "GRVMgram.Menu.SendAsSticker"
    case menuCopyId = "GRVMgram.Menu.CopyID"
    case menuCopyCallback = "GRVMgram.Menu.CopyCallback"
    case menuJumpBeginning = "GRVMgram.Menu.JumpBeginning"
    case menuOpenProfileId = "GRVMgram.Menu.OpenProfileID"
    case repeatUnavailable = "GRVMgram.Repeat.Unavailable"

    case confirmSendSticker = "GRVMgram.Confirm.SendSticker"
    case confirmSendGif = "GRVMgram.Confirm.SendGIF"
    case confirmSendVoice = "GRVMgram.Confirm.SendVoice"
    case storyGhostTitle = "GRVMgram.StoryGhost.Title"
    case storyGhostText = "GRVMgram.StoryGhost.Text"
    case storyGhostEnable = "GRVMgram.StoryGhost.Enable"
    case storyGhostOpen = "GRVMgram.StoryGhost.Open"

    case messageDetailsTitle = "GRVMgram.MessageDetails.Title"
    case messageDetailsPeerId = "GRVMgram.MessageDetails.PeerID"
    case messageDetailsNamespace = "GRVMgram.MessageDetails.Namespace"
    case messageDetailsMessageId = "GRVMgram.MessageDetails.MessageID"
    case messageDetailsStableId = "GRVMgram.MessageDetails.StableID"
    case messageDetailsDate = "GRVMgram.MessageDetails.Date"
    case messageDetailsThreadId = "GRVMgram.MessageDetails.ThreadID"
    case messageDetailsAuthor = "GRVMgram.MessageDetails.Author"
    case messageDetailsForwardDate = "GRVMgram.MessageDetails.ForwardDate"
    case messageDetailsForwardAuthor = "GRVMgram.MessageDetails.ForwardAuthor"
    case messageDetailsForwardSource = "GRVMgram.MessageDetails.ForwardSource"
    case messageDetailsForwardSourceMessage = "GRVMgram.MessageDetails.ForwardSourceMessage"
    case messageDetailsForwardSignature = "GRVMgram.MessageDetails.ForwardSignature"
    case messageDetailsEdited = "GRVMgram.MessageDetails.Edited"
    case messageDetailsViews = "GRVMgram.MessageDetails.Views"
    case messageDetailsForwards = "GRVMgram.MessageDetails.Forwards"
    case messageDetailsImage = "GRVMgram.MessageDetails.Image"
    case messageDetailsFile = "GRVMgram.MessageDetails.File"
    case messageDetailsMedia = "GRVMgram.MessageDetails.Media"
    case messageDetailsFileId = "GRVMgram.MessageDetails.File.ID"
    case messageDetailsFileMime = "GRVMgram.MessageDetails.File.MIME"
    case messageDetailsFileName = "GRVMgram.MessageDetails.File.Name"
    case messageDetailsFileSize = "GRVMgram.MessageDetails.File.Size"
    case messageDetailsFileDimensions = "GRVMgram.MessageDetails.File.Dimensions"
    case messageDetailsFileDuration = "GRVMgram.MessageDetails.File.Duration"

    case messageShotTitle = "GRVMgram.MessageShot.Title"
    case messageShotPreviewAccessibility = "GRVMgram.MessageShot.PreviewAccessibility"
    case messageShotTheme = "GRVMgram.MessageShot.Theme"
    case messageShotThemeCurrent = "GRVMgram.MessageShot.Theme.Current"
    case messageShotThemeLight = "GRVMgram.MessageShot.Theme.Light"
    case messageShotThemeDark = "GRVMgram.MessageShot.Theme.Dark"
    case messageShotBackground = "GRVMgram.MessageShot.Background"
    case messageShotDate = "GRVMgram.MessageShot.Date"
    case messageShotReactions = "GRVMgram.MessageShot.Reactions"
    case messageShotHeader = "GRVMgram.MessageShot.Header"
    case messageShotDecorations = "GRVMgram.MessageShot.Decorations"
    case messageShotReplies = "GRVMgram.MessageShot.Replies"
    case messageShotSpoilers = "GRVMgram.MessageShot.Spoilers"
    case messageShotCopy = "GRVMgram.MessageShot.Copy"
    case messageShotSave = "GRVMgram.MessageShot.Save"
    case messageShotSelectedUnavailable = "GRVMgram.MessageShot.SelectedUnavailable"
    case messageShotRenderFailed = "GRVMgram.MessageShot.RenderFailed"
    case messageShotPhotoAccessNotGranted = "GRVMgram.MessageShot.PhotoAccessNotGranted"
    case messageShotSaveFailed = "GRVMgram.MessageShot.SaveFailed"
    case messageShotPhotosTitle = "GRVMgram.MessageShot.Photos.Title"
    case messageShotPhotosText = "GRVMgram.MessageShot.Photos.Text"
    case messageShotChat = "GRVMgram.MessageShot.Chat"
    case messageShotQuotedReply = "GRVMgram.MessageShot.QuotedReply"
    case messageShotCustomReaction = "GRVMgram.MessageShot.CustomReaction"
    case messageShotStars = "GRVMgram.MessageShot.Stars"
    case messageShotBoost = "GRVMgram.MessageShot.Boost"
    case messageShotPhotoUnavailable = "GRVMgram.MessageShot.PhotoUnavailable"
    case messageShotFileUnavailable = "GRVMgram.MessageShot.FileUnavailable"
    case messageShotMediaUnavailable = "GRVMgram.MessageShot.MediaUnavailable"
    case messageShotReply = "GRVMgram.MessageShot.Reply"
    case messageShotMessageUnavailable = "GRVMgram.MessageShot.MessageUnavailable"
    case messageShotReplyMediaUnavailable = "GRVMgram.MessageShot.ReplyMediaUnavailable"

    case sendAsStickerError = "GRVMgram.SendAsSticker.Error"
    case peerCopyTelegramId = "GRVMgram.Peer.CopyTelegramID"
    case peerCopyBotApiId = "GRVMgram.Peer.CopyBotAPIID"
    case peerCreated = "GRVMgram.Peer.Created"
    case peerJoined = "GRVMgram.Peer.Joined"

    case otherTitle = "GRVMgram.Other.Title"
    case otherHeader = "GRVMgram.Other.Header"
    case streamerTitle = "GRVMgram.Streamer.Title"
    case streamerInfo = "GRVMgram.Streamer.Info"
    case streamerCover = "GRVMgram.Streamer.Cover"
    case streamerCoverAccessibility = "GRVMgram.Streamer.CoverAccessibility"
    case crashTitle = "GRVMgram.Crash.Title"
    case crashInfo = "GRVMgram.Crash.Info"
    case crashPromptTitle = "GRVMgram.Crash.Prompt.Title"
    case crashPromptText = "GRVMgram.Crash.Prompt.Text"
    case crashExport = "GRVMgram.Crash.Export"
    case crashNotNow = "GRVMgram.Crash.NotNow"
    case crashNoReports = "GRVMgram.Crash.NoReports"
    case crashSummary = "GRVMgram.Crash.Summary"
    case crashCleanupError = "GRVMgram.Crash.CleanupError"
    case crashShareError = "GRVMgram.Crash.ShareError"
    case resetTitle = "GRVMgram.Reset.Title"
    case resetText = "GRVMgram.Reset.Text"
    case resetAction = "GRVMgram.Reset.Action"

    case deleteOwnTitle = "GRVMgram.DeleteOwn.Title"
    case deleteOwnText = "GRVMgram.DeleteOwn.Text"
    case deleteOwnAction = "GRVMgram.DeleteOwn.Action"
    case deleteOwnResult = "GRVMgram.DeleteOwn.Result"
    case deleteOwnError = "GRVMgram.DeleteOwn.Error"
    case readError = "GRVMgram.Read.Error"
    case readUnavailable = "GRVMgram.Read.Unavailable"
    case callbackCopyFailed = "GRVMgram.Callback.CopyFailed"
    case jumpBeginningUnavailable = "GRVMgram.JumpBeginning.Unavailable"
    case burnTitle = "GRVMgram.Burn.Title"
    case burnText = "GRVMgram.Burn.Text"
    case burnAction = "GRVMgram.Burn.Action"
    case burnError = "GRVMgram.Burn.Error"
    case replayUnavailable = "GRVMgram.Replay.Unavailable"
    case replayRestoreFailed = "GRVMgram.Replay.RestoreFailed"
    case forwardLocalCopyUnsupported = "GRVMgram.ForwardLocalCopy.Unsupported"
    case forwardLocalCopyUnavailable = "GRVMgram.ForwardLocalCopy.Unavailable"
    case forwardLocalCopyRestoreFailed = "GRVMgram.ForwardLocalCopy.RestoreFailed"
    case forwardLocalCopyUploadFailed = "GRVMgram.ForwardLocalCopy.UploadFailed"
}

public struct GRVMgramStrings {
    public let languageCode: String

    private let values: [String: String]
    private let englishValues: [String: String]

    public init(_ presentationStrings: PresentationStrings) {
        let baseCode = presentationStrings.baseLanguageCode.lowercased()
        let languageCode = baseCode == "ru" || baseCode.hasPrefix("ru-") ? "ru" : "en"

        self.languageCode = languageCode
        self.englishValues = Self.english
        self.values = languageCode == "ru" ? Self.russian : Self.english
    }

    public subscript(_ key: GRVMgramStringKey) -> String {
        return self.values[key.rawValue]
            ?? self.englishValues[key.rawValue]
            ?? key.rawValue
    }

    public func format(_ key: GRVMgramStringKey, _ arguments: CVarArg...) -> String {
        return String(
            format: self[key],
            locale: Locale(identifier: self.languageCode),
            arguments: arguments
        )
    }

    private static let english = Self.load(languageCode: "en")
    private static let russian = Self.load(languageCode: "ru")

    private static func load(languageCode: String) -> [String: String] {
        guard
            let path = getAppBundle().path(
                forResource: "GRVMgram",
                ofType: "strings",
                inDirectory: nil,
                forLocalization: languageCode
            ),
            let values = NSDictionary(
                contentsOf: URL(fileURLWithPath: path)
            ) as? [String: String]
        else {
            return [:]
        }

        return values
    }
}
